{ pkgs, lib, config, ... }:
with lib;
{
  options.modules.cloneDefaultRepos = {
    enable = mkOption { type = types.bool; default = false; };
  };
  config = mkIf config.modules.cloneDefaultRepos.enable
    {

      home.file."git/txt" = { text = "generated by homemanager"; };


      systemd.user.services.cloneDefaultRepos =
        let
          cloneRepoScript =  pkgs.writeShellScript "cloneRepos.sh" ''
            ${pkgs.git}/bin/git clone https://github.com/marnyg/nixos-modules ~/git/nixos-modules;
            ${pkgs.git}/bin/git clone https://github.com/marnyg/nixos-wsl ~/git/nixos-wsl;
            ${pkgs.git}/bin/git clone https://github.com/marnyg/nixos ~/git/nixos;
            ${pkgs.git}/bin/git clone https://github.com/marnyg/nvim-conf ~/git/nvim;
          '';
        in
        {
          #WantedBy = [ "multi-user.target" ];
          ServiceConfig = { Type = "oneshot"; };
          Service = { ExexStart = "${cloneRepoScript}"; };
        };

      #script = ''
      #  ${pkgs.git}/bin/git clone https://github.com/marnyg/nixos-modules ~/git/nixos-modules;
      #  ${pkgs.git}/bin/git clone https://github.com/marnyg/nixos-wsl ~/git/nixos-wsl;
      #  ${pkgs.git}/bin/git clone https://github.com/marnyg/nixos ~/git/nixos;
      #  ${pkgs.git}/bin/git clone https://github.com/marnyg/nvim-conf ~/git/nvim;
      #'';
    };
}
